---
- hosts: eos
  gather_facts: no
  connection: network_cli
  tasks:
  - name: "Merge module attributes of given access-groups"
    eos_acl_interfaces:
      config:
        - name: Ethernet2
          access_groups:
            - afi: ipv4
              acls:
                - name: acl01
                  direction: in
            - afi: ipv6
              acls:
                - name: acl03
                  direction: out
      state: merged
